import crypto from "crypto";
import express from "express";
import { parseBenchmarkText, type BenchmarkType } from "./benchmarks";
import type { EngagementStore } from "./engagements";

export const EXECUTION_SCHEMA_VERSION = "1.0.0";
export const EXECUTION_POLICY_VERSION = "2026-07-20";

type Scope = "single_node" | "multi_node";
type JobStatus = "draft" | "awaiting_approval" | "queued" | "claimed" | "preparing" | "running" | "uploading" | "parsing" | "completed" | "completed_with_warnings" | "failed" | "cancelled" | "expired" | "rejected";

type SupportedParameter = { type: "integer" | "string" | "enum"; min?: number; max?: number; allowed?: string[]; pattern?: string };
export type BenchmarkDefinition = {
  id: string; schema_version: string; display_name: string; category: string; description: string; supported_scope: Scope[];
  minimum_gpu_count: number; maximum_gpu_count: number | null; requires_gpu: boolean; requires_nvlink: boolean; requires_infiniband: boolean; requires_mpi: boolean; requires_container_runtime: boolean;
  expected_executable: string; supported_parameters: Record<string, SupportedParameter>; default_parameters: Record<string, unknown>; validation_rules: string[]; estimated_duration_class: string; disruptive_level: string; requires_explicit_approval: boolean; parser_type: BenchmarkType; result_file_patterns: string[]; documentation_url: string; enabled: boolean;
};

type RunnerStatus = "pending" | "online" | "offline" | "revoked" | "incompatible";
type BenchmarkJob = { id: string; schema_version: string; engagement_id: string; benchmark_definition_id: string; display_name: string; created_at: string; created_by: string; approved_at: string | null; approved_by: string | null; expires_at: string; status: JobStatus; target_node_ids: string[]; scope: Scope; parameters: Record<string, unknown>; generated_command_preview: string; execution_policy_version: string; runner_claimed_at: string | null; runner_id: string | null; started_at: string | null; finished_at: string | null; cancel_requested_at: string | null; result_ids: string[]; failure_reason: string | null; simulated: boolean; audit_events: any[]; logs?: any[]; progress?: number | null };
type RunnerToken = { id: string; schema_version: string; token_hash: string; engagement_id: string; node_id: string; created_at: string; expires_at: string; created_by: string; revoked_at: string | null; status: "active" | "expired" | "revoked" | "used" };
type NodeRunner = { id: string; schema_version: string; node_id: string; engagement_id: string; runner_version: string; credential_hash: string; registered_at: string; last_seen_at: string; status: RunnerStatus; supported_benchmark_ids: string[]; capabilities: Record<string, unknown>; hostname_display: string | null; operating_system: string | null; architecture: string | null; gpu_count: number | null; container_runtime: string | null; mpi_available: boolean; nccl_tests_available: boolean; hpl_available: boolean; dcgm_available: boolean };

function ncclDef(id: string, name: string, exe: string): BenchmarkDefinition {
  return { id, schema_version: EXECUTION_SCHEMA_VERSION, display_name: name, category: "GPU collectives", description: `${name} smoke and performance execution through NCCL Tests adapter.`, supported_scope: ["single_node", "multi_node"], minimum_gpu_count: 1, maximum_gpu_count: null, requires_gpu: true, requires_nvlink: false, requires_infiniband: false, requires_mpi: false, requires_container_runtime: false, expected_executable: exe, supported_parameters: ncclParams(), default_parameters: { minimum_bytes: "8M", maximum_bytes: "128M", size_factor: 2, gpu_count: 1, warmup_iterations: 5, iterations: 5, data_type: "float", operation: exe }, validation_rules: ["typed parameters only", "no arbitrary flags", "single-node execution enabled first", "multi-node requires explicit approval and dry-run plan"], estimated_duration_class: "short", disruptive_level: "low", requires_explicit_approval: false, parser_type: "nccl", result_file_patterns: ["*.txt", "*.log"], documentation_url: "internal:docs/BENCHMARK_EXECUTION_PLANE.md#nccl-tests", enabled: true };
}
function ncclParams(): Record<string, SupportedParameter> { return { minimum_bytes: { type: "string", allowed: ["1M", "8M", "16M"] }, maximum_bytes: { type: "string", allowed: ["64M", "128M", "1G", "8G"] }, size_factor: { type: "integer", min: 2, max: 4 }, gpu_count: { type: "integer", min: 1, max: 16 }, warmup_iterations: { type: "integer", min: 1, max: 20 }, iterations: { type: "integer", min: 1, max: 1000 }, data_type: { type: "enum", allowed: ["half", "float", "double", "int"] }, operation: { type: "enum", allowed: ["all_reduce_perf", "all_gather_perf", "reduce_scatter_perf", "broadcast_perf"] } }; }
export const benchmarkDefinitions: BenchmarkDefinition[] = [
  ncclDef("nccl-all-reduce", "NCCL AllReduce", "all_reduce_perf"), ncclDef("nccl-all-gather", "NCCL AllGather", "all_gather_perf"), ncclDef("nccl-reduce-scatter", "NCCL ReduceScatter", "reduce_scatter_perf"), ncclDef("nccl-broadcast", "NCCL Broadcast", "broadcast_perf"),
  { id: "nvidia-hpl", schema_version: EXECUTION_SCHEMA_VERSION, display_name: "NVIDIA HPL", category: "Compute", description: "NVIDIA HPL execution through an approved local container/launcher policy.", supported_scope: ["single_node", "multi_node"], minimum_gpu_count: 1, maximum_gpu_count: null, requires_gpu: true, requires_nvlink: false, requires_infiniband: false, requires_mpi: true, requires_container_runtime: true, expected_executable: "hpl.sh", supported_parameters: { gpu_count: { type: "integer", min: 1, max: 16 }, problem_size: { type: "integer", min: 1024, max: 2000000 }, block_size: { type: "integer", min: 64, max: 1024 }, process_grid_p: { type: "integer", min: 1, max: 64 }, process_grid_q: { type: "integer", min: 1, max: 64 }, preset: { type: "enum", allowed: ["smoke", "balanced", "large"] }, container_image: { type: "enum", allowed: ["nvcr.io/nvidia/hpc-benchmarks:25.04"] } }, default_parameters: { preset: "smoke", gpu_count: 1, problem_size: 4096, block_size: 256, process_grid_p: 1, process_grid_q: 1, container_image: "nvcr.io/nvidia/hpc-benchmarks:25.04" }, validation_rules: ["approved image only", "explicit approval required"], estimated_duration_class: "long", disruptive_level: "high", requires_explicit_approval: true, parser_type: "hpl", result_file_patterns: ["HPL*.out", "*.log"], documentation_url: "internal:docs/BENCHMARK_EXECUTION_PLANE.md#nvidia-hpl", enabled: true },
  inferenceDef("triton-perf-analyzer", "Triton Performance Analyzer", "triton_perf_analyzer", "perf_analyzer"), inferenceDef("genai-perf", "GenAI-Perf", "genai_perf", "genai-perf"),
  { id: "dcgm-diag-level-1", schema_version: EXECUTION_SCHEMA_VERSION, display_name: "DCGM Level 1 Diagnostics", category: "Diagnostics", description: "DCGM level 1 diagnostics only; higher levels are out of scope.", supported_scope: ["single_node"], minimum_gpu_count: 1, maximum_gpu_count: null, requires_gpu: true, requires_nvlink: false, requires_infiniband: false, requires_mpi: false, requires_container_runtime: false, expected_executable: "dcgmi", supported_parameters: { gpu_count: { type: "integer", min: 1, max: 16 } }, default_parameters: { gpu_count: 1 }, validation_rules: ["level 1 only", "explicit approval required"], estimated_duration_class: "medium", disruptive_level: "medium", requires_explicit_approval: true, parser_type: "nccl", result_file_patterns: ["dcgm*.txt", "*.log"], documentation_url: "internal:docs/BENCHMARK_EXECUTION_PLANE.md#dcgm", enabled: true },
];
function inferenceDef(id: string, name: string, parser: BenchmarkType, exe: string): BenchmarkDefinition { return { id, schema_version: EXECUTION_SCHEMA_VERSION, display_name: name, category: "Inference", description: `${name} import-first execution policy; enabled only with approved local model configuration.`, supported_scope: ["single_node"], minimum_gpu_count: 1, maximum_gpu_count: null, requires_gpu: true, requires_nvlink: false, requires_infiniband: false, requires_mpi: false, requires_container_runtime: false, expected_executable: exe, supported_parameters: { model_name: { type: "string", pattern: "^[A-Za-z0-9._/-]{1,120}$" }, concurrency_start: { type: "integer", min: 1, max: 1024 }, concurrency_end: { type: "integer", min: 1, max: 1024 }, concurrency_step: { type: "integer", min: 1, max: 128 }, measurement_interval_ms: { type: "integer", min: 100, max: 600000 }, request_count: { type: "integer", min: 1, max: 100000 }, batch_size: { type: "integer", min: 1, max: 1024 } }, default_parameters: { concurrency_start: 1, concurrency_end: 4, concurrency_step: 1, measurement_interval_ms: 10000, request_count: 100, batch_size: 1 }, validation_rules: ["approved model configuration only", "no downloads"], estimated_duration_class: "medium", disruptive_level: "low", requires_explicit_approval: false, parser_type: parser, result_file_patterns: ["*.csv", "*.json", "*.txt"], documentation_url: "internal:docs/BENCHMARK_EXECUTION_PLANE.md#inference", enabled: true }; }

function hashSecret(secret: string, kind: string): string { return crypto.createHash("sha256").update(`gpu-validator-${kind}-v1:${secret}`).digest("hex"); }
function safeEqualDigest(left: string, right: string) { const a = Buffer.from(left, "hex"); const b = Buffer.from(right, "hex"); return a.length === b.length && crypto.timingSafeEqual(a, b); }
function now() { return new Date().toISOString(); }
function publicToken(token: RunnerToken) { const { token_hash: _h, ...safe } = token; return safe; }
function publicRunner(runner: NodeRunner) { const { credential_hash: _h, ...safe } = runner; return safe; }
function doc(store: EngagementStore): any { const document: any = store.read(); document.runner_tokens ??= []; document.node_runners ??= []; document.benchmark_jobs ??= []; return document; }
function write(store: EngagementStore, document: any) { (store as any).write(document); }
function err(res: express.Response, status: number, message: string) { return res.status(status).set("Cache-Control", "no-store").json({ error: message }); }
function findDef(id: string) { const def = benchmarkDefinitions.find((item) => item.id === id && item.enabled); if (!def) throw new Error("Unsupported benchmark definition."); return def; }
function hasUnsafe(value: unknown): boolean { return typeof value === "string" && /[;&|`$<>\n\r\\]/.test(value); }
function validateParams(def: BenchmarkDefinition, input: Record<string, unknown>) { if (Object.keys(input).some((key) => !(key in def.supported_parameters))) throw new Error("Unsupported benchmark parameter."); const out = { ...def.default_parameters, ...input }; for (const [key, rule] of Object.entries(def.supported_parameters)) { const value = out[key]; if (hasUnsafe(value)) throw new Error("Unsafe shell-like parameter value rejected."); if (rule.type === "integer") { const num = Number(value); if (!Number.isInteger(num) || (rule.min !== undefined && num < rule.min) || (rule.max !== undefined && num > rule.max)) throw new Error(`${key} is outside allowed bounds.`); out[key] = num; } else if (rule.allowed && !rule.allowed.includes(String(value))) throw new Error(`${key} is not in the allowlist.`); else if (rule.pattern && !new RegExp(rule.pattern).test(String(value))) throw new Error(`${key} failed validation.`); } return out; }
function commandPreview(def: BenchmarkDefinition, params: Record<string, unknown>) { if (def.id.startsWith("nccl-")) return `${def.expected_executable} -b ${params.minimum_bytes} -e ${params.maximum_bytes} -f ${params.size_factor} -g ${params.gpu_count} -w ${params.warmup_iterations} -n ${params.iterations}`; if (def.id === "nvidia-hpl") return `hpl.sh --preset ${params.preset} --gpus ${params.gpu_count} --image approved:${params.container_image}`; if (def.id === "dcgm-diag-level-1") return `dcgmi diag -r 1 --gpu-count ${params.gpu_count}`; return `${def.expected_executable} --model ${params.model_name ?? "approved-model"} --concurrency-range ${params.concurrency_start}-${params.concurrency_end}`; }
function runnerForToken(document: any, bearer: string): NodeRunner | null { const digest = hashSecret(bearer, "runner-credential"); return (document.node_runners as NodeRunner[]).find((runner) => runner.status === "online" && safeEqualDigest(runner.credential_hash, digest)) ?? null; }
function redact(text: string) { return text.replace(/Authorization:\s*Bearer\s+\S+/gi, "Authorization: Bearer [redacted]").replace(/token=([^\s]+)/gi, "token=[redacted]").replace(/[\u001b\u009b][[\]()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, "").slice(0, 16_384); }

export function registerExecutionRoutes(app: express.Express, store: EngagementStore) {
  app.get("/api/v1/benchmark-definitions", (_req, res) => res.set("Cache-Control", "no-store").json({ definitions: benchmarkDefinitions }));

  app.post("/api/v1/engagements/:engagementId/nodes/:nodeId/runner-tokens", (req, res) => { try { const document = doc(store); if (!document.nodes.some((n: any) => n.engagement_id === req.params.engagementId && n.id === req.params.nodeId)) return err(res, 404, "Engagement node not found."); const plaintext = `gvr_${crypto.randomBytes(32).toString("base64url")}`; const created = now(); const token: RunnerToken = { id: `rnt_${crypto.randomUUID()}`, schema_version: EXECUTION_SCHEMA_VERSION, token_hash: hashSecret(plaintext, "runner-registration"), engagement_id: req.params.engagementId, node_id: req.params.nodeId, created_at: created, expires_at: new Date(Date.now() + 86_400_000).toISOString(), created_by: req.get("x-reviewer-email") ?? "reviewer", revoked_at: null, status: "active" }; document.runner_tokens.push(token); write(store, document); return res.status(201).json({ token: publicToken(token), plaintext }); } catch (e) { return err(res, 400, e instanceof Error ? e.message : "Runner token failed."); } });
  app.post("/api/v1/engagements/:engagementId/nodes/:nodeId/runner-tokens/:tokenId/revoke", (req, res) => { const document = doc(store); const token = document.runner_tokens.find((t: RunnerToken) => t.id === req.params.tokenId && t.engagement_id === req.params.engagementId && t.node_id === req.params.nodeId); if (!token) return err(res, 404, "Runner token not found."); token.status = "revoked"; token.revoked_at = now(); write(store, document); return res.json({ token: publicToken(token) }); });

  app.post("/api/v1/runners/register", (req, res) => { const document = doc(store); const token = document.runner_tokens.find((t: RunnerToken) => t.node_id === req.body?.node_id && t.status === "active" && new Date(t.expires_at).getTime() > Date.now() && safeEqualDigest(t.token_hash, hashSecret(String(req.body?.token ?? ""), "runner-registration"))); if (!token) return err(res, 401, "Runner registration failed."); const bearer = `gvc_${crypto.randomBytes(32).toString("base64url")}`; const runner: NodeRunner = { id: `rnr_${crypto.randomUUID()}`, schema_version: EXECUTION_SCHEMA_VERSION, node_id: token.node_id, engagement_id: token.engagement_id, runner_version: String(req.body?.runner_version ?? "unknown"), credential_hash: hashSecret(bearer, "runner-credential"), registered_at: now(), last_seen_at: now(), status: "online", supported_benchmark_ids: Array.isArray(req.body?.supported_benchmark_ids) ? req.body.supported_benchmark_ids.map(String) : [], capabilities: req.body?.capabilities ?? {}, hostname_display: req.body?.hostname_display ?? null, operating_system: req.body?.operating_system ?? null, architecture: req.body?.architecture ?? null, gpu_count: Number(req.body?.capabilities?.gpu_count ?? req.body?.gpu_count ?? 0) || null, container_runtime: req.body?.container_runtime ?? null, mpi_available: req.body?.capabilities?.mpi_available === true, nccl_tests_available: req.body?.capabilities?.nccl_tests_available === true, hpl_available: req.body?.capabilities?.hpl_available === true, dcgm_available: req.body?.capabilities?.dcgm_available === true }; token.status = "used"; document.node_runners.push(runner); write(store, document); return res.status(201).json({ runner: publicRunner(runner), credential: { runner_id: runner.id, bearer_token: bearer } }); });
  function requireRunner(req: express.Request, res: express.Response): [any, NodeRunner] | null { const auth = req.get("authorization") ?? ""; if (!auth.startsWith("Bearer ")) { err(res, 401, "Runner authentication required."); return null; } const document = doc(store); const runner = runnerForToken(document, auth.slice(7).trim()); if (!runner) { err(res, 401, "Runner authentication required."); return null; } runner.last_seen_at = now(); return [document, runner]; }
  app.post("/api/v1/runners/heartbeat", (req, res) => { const got = requireRunner(req, res); if (!got) return; const [document, runner] = got; runner.capabilities = { ...runner.capabilities, ...(req.body?.capabilities ?? {}) }; write(store, document); return res.json({ runner: publicRunner(runner) }); });
  app.post("/api/v1/runners/jobs/claim", (req, res) => { const got = requireRunner(req, res); if (!got) return; const [document, runner] = got; const candidate = document.benchmark_jobs.find((job: BenchmarkJob) => job.status === "queued" && job.target_node_ids.includes(runner.node_id) && new Date(job.expires_at).getTime() > Date.now()); if (!candidate) { document.benchmark_jobs.forEach((job: BenchmarkJob) => { if (job.status === "queued" && new Date(job.expires_at).getTime() <= Date.now()) job.status = "expired"; }); write(store, document); return res.json({ job: null }); } candidate.status = "claimed"; candidate.runner_claimed_at = now(); candidate.runner_id = runner.id; candidate.audit_events.push({ at: now(), event: "claimed", runner_id: runner.id }); write(store, document); return res.json({ job: candidate }); });
  app.post("/api/v1/runners/jobs/:jobId/status", (req, res) => { const got = requireRunner(req, res); if (!got) return; const [document, runner] = got; const job = document.benchmark_jobs.find((j: BenchmarkJob) => j.id === req.params.jobId && j.runner_id === runner.id); if (!job) return err(res, 404, "Benchmark job not found for runner."); const status = String(req.body?.status ?? ""); if (!["preparing", "running", "uploading", "parsing"].includes(status)) return err(res, 400, "Unsupported runner status."); job.status = status as JobStatus; if (status === "running" && !job.started_at) job.started_at = now(); job.progress = Number(req.body?.progress ?? job.progress ?? 0); job.audit_events.push({ at: now(), event: status, progress: job.progress }); write(store, document); return res.json({ job }); });
  app.post("/api/v1/runners/jobs/:jobId/logs", (req, res) => { const got = requireRunner(req, res); if (!got) return; const [document, runner] = got; const job = document.benchmark_jobs.find((j: BenchmarkJob) => j.id === req.params.jobId && j.runner_id === runner.id); if (!job) return err(res, 404, "Benchmark job not found for runner."); job.logs ??= []; job.logs.push({ at: now(), runner_id: runner.id, chunk: redact(String(req.body?.chunk ?? "")) }); job.logs = job.logs.slice(-200); write(store, document); return res.json({ accepted: true }); });
  app.post("/api/v1/runners/jobs/:jobId/fail", (req, res) => { const got = requireRunner(req, res); if (!got) return; const [document, runner] = got; const job = document.benchmark_jobs.find((j: BenchmarkJob) => j.id === req.params.jobId && j.runner_id === runner.id); if (!job) return err(res, 404, "Benchmark job not found for runner."); job.status = "failed"; job.failure_reason = redact(String(req.body?.reason ?? "Runner reported failure.")); job.finished_at = now(); write(store, document); return res.json({ job }); });
  app.post("/api/v1/runners/jobs/:jobId/complete", (req, res) => { const got = requireRunner(req, res); if (!got) return; const [document, runner] = got; const job = document.benchmark_jobs.find((j: BenchmarkJob) => j.id === req.params.jobId && j.runner_id === runner.id); if (!job) return err(res, 404, "Benchmark job not found for runner."); const def = findDef(job.benchmark_definition_id); const output = String(req.body?.output ?? ""); const parsed = parseBenchmarkText(def.parser_type, output, String(req.body?.filename ?? "runner-output.txt")); const sha = crypto.createHash("sha256").update(output).digest("hex"); const run: any = { engagement_id: job.engagement_id, node_id: runner.node_id, benchmark_type: def.parser_type, benchmark_version: parsed.benchmark_version, tool_version: parsed.tool_version, collected_at: parsed.collected_at, uploaded_at: now(), simulated: job.simulated, input_file: String(req.body?.filename ?? "runner-output.txt").replace(/[<>"'`\n\r\t]/g, ""), sha256: sha, warnings: parsed.warnings, metrics: parsed.metrics, raw_storage_id: `job_${job.id}_${sha.slice(0, 12)}`, provenance: { ...parsed.provenance, simulated: job.simulated, source_kind: req.body?.source_kind ?? "runner_uploaded_result", benchmark_job_id: job.id } }; const accepted = (store as any).acceptBenchmarkRun(run); const fresh = doc(store); const freshJob = fresh.benchmark_jobs.find((j: BenchmarkJob) => j.id === job.id); freshJob.status = accepted.status === "accepted" ? "completed" : "completed_with_warnings"; freshJob.result_ids.push(accepted.id); freshJob.finished_at = now(); freshJob.audit_events.push({ at: now(), event: "completed", result_id: accepted.id }); write(store, fresh); return res.json({ job: freshJob, benchmark: accepted }); });

  app.post("/api/v1/engagements/:engagementId/benchmark-jobs", (req, res) => { try { const document = doc(store); if (!document.engagements.some((e: any) => e.id === req.params.engagementId)) return err(res, 404, "Engagement not found."); const def = findDef(String(req.body?.benchmark_definition_id)); const targets = Array.isArray(req.body?.target_node_ids) ? req.body.target_node_ids.map(String) : []; if (!targets.length) throw new Error("At least one benchmark target is required."); for (const nodeId of targets) if (!document.nodes.some((n: any) => n.engagement_id === req.params.engagementId && n.id === nodeId)) throw new Error("Invalid target node."); const scope: Scope = targets.length > 1 ? "multi_node" : "single_node"; if (scope === "multi_node" && !def.supported_scope.includes("multi_node")) throw new Error("Benchmark does not support multi-node scope."); const runners = document.node_runners.filter((r: NodeRunner) => targets.includes(r.node_id) && r.status === "online"); if (runners.length < targets.length) throw new Error("Capability mismatch: target runner is not online."); if (runners.some((r: NodeRunner) => !r.supported_benchmark_ids.includes(def.id))) throw new Error("Capability mismatch: runner does not support benchmark."); const params = validateParams(def, req.body?.parameters ?? {}); const requiresApproval = def.requires_explicit_approval || scope === "multi_node" || def.disruptive_level !== "low" || (def.id.startsWith("nccl-") && Number(params.gpu_count) > 8); const job: BenchmarkJob = { id: `job_${crypto.randomUUID()}`, schema_version: EXECUTION_SCHEMA_VERSION, engagement_id: req.params.engagementId, benchmark_definition_id: def.id, display_name: def.display_name, created_at: now(), created_by: req.get("x-reviewer-email") ?? "reviewer", approved_at: requiresApproval ? null : now(), approved_by: requiresApproval ? null : (req.get("x-reviewer-email") ?? "reviewer"), expires_at: new Date(Date.now() + 3_600_000).toISOString(), status: requiresApproval ? "awaiting_approval" : "queued", target_node_ids: targets, scope, parameters: params, generated_command_preview: commandPreview(def, params), execution_policy_version: EXECUTION_POLICY_VERSION, runner_claimed_at: null, runner_id: null, started_at: null, finished_at: null, cancel_requested_at: null, result_ids: [], failure_reason: scope === "multi_node" ? "Multi-node execution planned but not enabled; dry-run plan only." : null, simulated: req.body?.simulated === true, audit_events: [{ at: now(), event: "created", requires_approval: requiresApproval }] }; document.benchmark_jobs.push(job); write(store, document); return res.status(201).json({ job }); } catch (e) { return err(res, 400, e instanceof Error ? e.message : "Benchmark job creation failed."); } });
  app.get("/api/v1/engagements/:engagementId/benchmark-jobs", (req, res) => { const document = doc(store); return res.json({ jobs: document.benchmark_jobs.filter((j: BenchmarkJob) => j.engagement_id === req.params.engagementId) }); });
  app.get("/api/v1/engagements/:engagementId/benchmark-jobs/:jobId", (req, res) => { const document = doc(store); const job = document.benchmark_jobs.find((j: BenchmarkJob) => j.engagement_id === req.params.engagementId && j.id === req.params.jobId); if (!job) return err(res, 404, "Benchmark job not found."); if (job.status === "queued" && new Date(job.expires_at).getTime() <= Date.now()) { job.status = "expired"; write(store, document); } return res.json({ job }); });
  app.post("/api/v1/engagements/:engagementId/benchmark-jobs/:jobId/approve", (req, res) => { const document = doc(store); const job = document.benchmark_jobs.find((j: BenchmarkJob) => j.engagement_id === req.params.engagementId && j.id === req.params.jobId); if (!job) return err(res, 404, "Benchmark job not found."); if (job.status !== "awaiting_approval") return err(res, 400, "Job is not awaiting approval."); job.status = "queued"; job.approved_at = now(); job.approved_by = req.get("x-reviewer-email") ?? "reviewer"; job.audit_events.push({ at: now(), event: "approved" }); write(store, document); return res.json({ job }); });
  app.post("/api/v1/engagements/:engagementId/benchmark-jobs/:jobId/cancel", (req, res) => { const document = doc(store); const job = document.benchmark_jobs.find((j: BenchmarkJob) => j.engagement_id === req.params.engagementId && j.id === req.params.jobId); if (!job) return err(res, 404, "Benchmark job not found."); job.status = "cancelled"; job.cancel_requested_at = now(); job.audit_events.push({ at: now(), event: "cancelled" }); write(store, document); return res.json({ job }); });
}
