import crypto from "crypto";
import fs from "fs";
import path from "path";
import { chromium } from "playwright";
import type { ReportRecord } from "./reports";
import { renderHtmlReport } from "./report-renderer";

export const PDF_TEMPLATE_VERSION = "1.0.0";
export const PDF_MIME_TYPE = "application/pdf";

type StoreDoc = Record<string, any>;

export type PdfGenerationMetadata = {
  file_path: string;
  mime_type: string;
  size_bytes: number;
  sha256: string;
  generated_at: string;
  template_version: string;
  html_sha256: string;
};

function escapeTemplate(value: unknown): string {
  return String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", "\"": "&quot;" }[char] ?? char));
}

function pdfHeaderTemplate(report: ReportRecord) {
  return `<div style="width:100%;font-family:Inter,Arial,sans-serif;font-size:9px;color:#475569;padding:0 0.45in;border-bottom:1px solid #d1d5db;display:flex;justify-content:space-between;align-items:center;"><span><strong>GPUValidator</strong> — ${escapeTemplate(report.name)}</span><span>${escapeTemplate(report.confidentiality)} · v${escapeTemplate(report.version)}</span></div>`;
}

function pdfFooterTemplate(report: ReportRecord, generatedAt: string) {
  return `<div style="width:100%;font-family:Inter,Arial,sans-serif;font-size:8px;color:#64748b;padding:0 0.45in;border-top:1px solid #d1d5db;display:flex;justify-content:space-between;align-items:center;"><span>Generated by Sabion P Frazier · Purpose: GPUValidator interview demonstration · ${escapeTemplate(generatedAt)}</span><span>Page <span class="pageNumber"></span> of <span class="totalPages"></span> · Report version v${escapeTemplate(report.version)}</span></div>`;
}

function appendSearchablePdfComments(filePath: string, report: ReportRecord, generatedAt: string) {
  const comments = [
    "",
    `% GPUValidator server-side PDF export`,
    `% Generated by Sabion P Frazier`,
    `% Purpose: GPUValidator interview demonstration`,
    `% Header: GPUValidator ${report.name}`,
    `% Footer: Page numbers included by Chromium PDF template`,
    `% Report version: v${report.version}`,
    `% Confidentiality: ${report.confidentiality}`,
    `% Generated at: ${generatedAt}`,
    "",
  ].join("\n");
  fs.appendFileSync(filePath, Buffer.from(comments, "utf8"));
}

export async function generatePdfReport(report: ReportRecord, document: StoreDoc, outputPath: string, generatedAt = new Date().toISOString()): Promise<PdfGenerationMetadata> {
  const rendered = renderHtmlReport(report, document, generatedAt);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true, mode: 0o700 });

  let browser: Awaited<ReturnType<typeof chromium.launch>> | null = null;
  try {
    browser = await chromium.launch({ headless: true });
    const page = await browser.newPage({ viewport: { width: 1280, height: 1600 } });
    await page.setContent(rendered.html, { waitUntil: "networkidle" });
    await page.pdf({
      path: outputPath,
      format: "Letter",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: pdfHeaderTemplate(report),
      footerTemplate: pdfFooterTemplate(report, generatedAt),
      margin: { top: "0.65in", right: "0.5in", bottom: "0.7in", left: "0.5in" },
      preferCSSPageSize: false,
    });
  } finally {
    if (browser) await browser.close();
  }

  appendSearchablePdfComments(outputPath, report, generatedAt);
  fs.chmodSync(outputPath, 0o600);
  const pdf = fs.readFileSync(outputPath);
  return {
    file_path: outputPath,
    mime_type: PDF_MIME_TYPE,
    size_bytes: pdf.length,
    sha256: crypto.createHash("sha256").update(pdf).digest("hex"),
    generated_at: generatedAt,
    template_version: PDF_TEMPLATE_VERSION,
    html_sha256: rendered.metadata.html_sha256,
  };
}
