import crypto from "crypto";
import { deriveLiveGpuInventory } from "../portal/agents";
import type { ReportRecord } from "./reports";

export const reportHtmlSections = [
  "Cover Page",
  "Document Control",
  "Generated By",
  "Purpose",
  "Executive Summary",
  "Environment Summary",
  "Hardware Inventory",
  "GPU Inventory",
  "Validation Results",
  "Benchmark Results",
  "Findings",
  "Risks",
  "Recommended Remediation",
  "Evidence References",
  "Report Provenance",
  "Appendices",
] as const;

type StoreDoc = Record<string, any>;
type ValidationDetail = { validation: any; jobs: any[]; results: any[] };
type RenderedReport = {
  html: string;
  metadata: {
    report_id: string;
    generated_at: string;
    html_sha256: string;
    source_lineage: {
      agent_ids: string[];
      node_ids: string[];
      gpu_ids: string[];
      validation_ids: string[];
      benchmark_ids: string[];
      evidence_ids: string[];
    };
  };
};

const missing = {
  notCollected: "Not collected",
  notAvailable: "Not available",
  notSupported: "Not supported",
  validationNotRun: "Validation not run",
};

function esc(value: unknown): string {
  return String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", "\"": "&quot;" }[char] ?? char));
}
function present(value: unknown, fallback = missing.notCollected): string {
  if (value === undefined || value === null || value === "") return fallback;
  return esc(value);
}
function unique(values: unknown[]): string[] {
  return [...new Set(values.map((value) => String(value ?? "").trim()).filter(Boolean))];
}
function iso(value: unknown): string {
  if (!value) return missing.notCollected;
  const parsed = new Date(String(value));
  return Number.isNaN(parsed.getTime()) ? esc(value) : parsed.toISOString();
}
function validationDetails(document: StoreDoc): ValidationDetail[] {
  const validations = Array.isArray(document.validations) ? document.validations : [];
  const jobs = Array.isArray(document.validation_jobs) ? document.validation_jobs : [];
  const results = Array.isArray(document.validation_results) ? document.validation_results : [];
  return validations.map((validation: any) => ({
    validation,
    jobs: jobs.filter((job: any) => job.validation_id === validation.id),
    results: results.filter((result: any) => result.validation_id === validation.id),
  }));
}
function selectedValidations(report: ReportRecord, document: StoreDoc): ValidationDetail[] {
  const all = validationDetails(document);
  if (report.validation_ids?.length) return all.filter((detail) => report.validation_ids.includes(detail.validation.id));
  if (report.scope_type === "validation_run" && report.scope_id) return all.filter((detail) => detail.validation.id === report.scope_id);
  if (report.scope_type === "agent" && report.scope_id) return all.filter((detail) => detail.validation.agent_id === report.scope_id);
  return all;
}
function selectedAgents(report: ReportRecord, document: StoreDoc, validations: ValidationDetail[]): any[] {
  const agents = Array.isArray(document.validation_agents) ? document.validation_agents : [];
  const ids = new Set(unique([...report.agent_ids, ...validations.map((detail) => detail.validation.agent_id)]));
  if (ids.size) return agents.filter((agent: any) => ids.has(agent.id));
  if (report.scope_type === "agent" && report.scope_id) return agents.filter((agent: any) => agent.id === report.scope_id);
  return agents;
}
function selectedBenchmarks(report: ReportRecord, document: StoreDoc): any[] {
  const benchmarks = Array.isArray(document.benchmark_runs) ? document.benchmark_runs : [];
  if (report.benchmark_ids?.length) return benchmarks.filter((run: any) => report.benchmark_ids.includes(run.id));
  if (report.scope_type === "benchmark_run" && report.scope_id) return benchmarks.filter((run: any) => run.id === report.scope_id);
  return benchmarks;
}
function selectedEvidence(report: ReportRecord, document: StoreDoc, validations: ValidationDetail[]): any[] {
  const records = Array.isArray(document.evidence_records) ? document.evidence_records : [];
  const validationIds = new Set(validations.map((detail) => detail.validation.id));
  if (report.evidence_ids?.length) return records.filter((record: any) => report.evidence_ids.includes(record.id));
  return records.filter((record: any) => !record.validation_id || validationIds.has(record.validation_id));
}
function table(headers: string[], rows: string[][], empty: string) {
  return `<table><thead><tr>${headers.map((header) => `<th>${esc(header)}</th>`).join("")}</tr></thead><tbody>${rows.length ? rows.map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`).join("") : `<tr><td colspan="${headers.length}">${esc(empty)}</td></tr>`}</tbody></table>`;
}
function section(title: string, body: string) {
  return `<section class="report-page"><h2>${esc(title)}</h2>${body}</section>`;
}
function severity(label: string, text: string) {
  return `<div class="severity-callout severity-${esc(label.toLowerCase())}"><strong>${esc(label)}:</strong> ${esc(text)}</div>`;
}

export function renderHtmlReport(report: ReportRecord, document: StoreDoc, generatedAt = new Date().toISOString()): RenderedReport {
  const validations = selectedValidations(report, document).map((detail) => ({
    ...detail,
    validation: { job_ids: detail.jobs.map((job) => job.id), ...detail.validation },
    results: detail.results.map((result) => ({
      stderr: "",
      ...result,
      command_evidence: { command_type: result.command_evidence?.command_type ?? result.job_id ?? "unknown", argv: Array.isArray(result.command_evidence?.argv) ? result.command_evidence.argv : [result.command_evidence?.command_type ?? result.job_id ?? "unknown"], ...(result.command_evidence ?? {}) },
    })),
  }));
  const agents = selectedAgents(report, document, validations);
  const benchmarks = selectedBenchmarks(report, document);
  const evidence = selectedEvidence(report, document, validations);
  const inventory = deriveLiveGpuInventory(agents, validations);
  const validationIds = unique([...report.validation_ids, ...validations.map((detail) => detail.validation.id)]);
  const benchmarkIds = unique([...report.benchmark_ids, ...benchmarks.map((run) => run.id)]);
  const agentIds = unique([...report.agent_ids, ...agents.map((agent) => agent.id), ...validations.map((detail) => detail.validation.agent_id)]);
  const nodeIds = unique([...report.node_ids, ...agents.map((agent) => agent.hostname ?? agent.node_id), ...inventory.map((gpu) => gpu.nodeId ?? gpu.nodeName)]);
  const gpuIds = unique([...report.gpu_ids, ...inventory.map((gpu) => gpu.uuid ?? gpu.id)]);
  const evidenceIds = unique([...report.evidence_ids, ...evidence.map((record) => record.id), ...validations.flatMap((detail) => detail.results.map((result) => result.id))]);
  const validationRows = validations.flatMap((detail) => detail.results.length ? detail.results.map((result) => [
    present(detail.validation.id, missing.validationNotRun),
    present(detail.validation.profile, missing.notAvailable),
    present(result.command_evidence?.command_type ?? result.job_id, missing.notAvailable),
    present(result.state, missing.validationNotRun),
    present(result.structured_result?.driver_version ?? result.structured_result?.cuda_version ?? result.stdout?.slice(0, 120), missing.notCollected),
  ]) : [[present(detail.validation.id), present(detail.validation.profile), missing.notAvailable, present(detail.validation.state, missing.validationNotRun), missing.notCollected]]);
  const benchmarkRows = benchmarks.map((run) => [present(run.id), present(run.benchmark_type), present(run.status), present(run.metrics?.bus_bandwidth_gbps ?? run.metrics?.avg_bus_bandwidth ?? run.metrics?.throughput, missing.notCollected), present(run.node_id, missing.notAvailable)]);
  const unresolvedBenchmarkRows = report.benchmark_ids.filter((id) => !benchmarks.some((run) => run.id === id)).map((id) => [esc(id), missing.notAvailable, missing.notAvailable, missing.notCollected, missing.notAvailable]);
  const gpuRows = inventory.map((gpu) => [present(gpu.nodeName), present(gpu.gpuIndex), present(gpu.model), present(gpu.uuid), present(gpu.memoryTotal), present(gpu.driverVersion), present(gpu.cudaVersion, missing.notCollected)]);
  const hardwareRows = agents.map((agent) => [present(agent.name), present(agent.hostname), present(agent.status), present(agent.gpu_count, missing.notCollected), Array.isArray(agent.capabilities) ? agent.capabilities.map((cap: any) => `${cap.name}: ${cap.available ? "available" : missing.notSupported}`).join("; ") : missing.notCollected]);
  const findingRows = (report.finding_ids?.length ? report.finding_ids : validations.filter((detail) => ["failed", "timed_out", "cancelled"].includes(detail.validation.state)).map((detail) => detail.validation.id)).map((finding) => [present(finding), "Observation", "Review selected validation evidence and benchmark context."]);
  const evidenceRows = evidence.map((record) => [present(record.id), present(record.node_id), present(record.ingestion_status), present(record.collected_count, missing.notCollected), present(record.missing_count, missing.notCollected), present(record.storage_key, missing.notAvailable)]);
  const css = `
    @page { margin: 0.75in; @bottom-center { content: "GPUValidator • Page " counter(page) " of " counter(pages); } }
    * { box-sizing: border-box; }
    body { margin: 0; background: #e5e7eb; color: #111827; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    .report-page { width: min(100%, 980px); margin: 24px auto; padding: 48px; background: white; border-top: 6px solid #76b900; box-shadow: 0 12px 30px rgba(15, 23, 42, 0.12); page-break-after: always; }
    .brand { color: #355f00; font-weight: 800; letter-spacing: 0.08em; text-transform: uppercase; }
    h1 { font-size: 44px; line-height: 1.05; margin: 18px 0; color: #0f172a; }
    h2 { color: #0f172a; border-bottom: 2px solid #76b900; padding-bottom: 8px; margin-top: 0; }
    h3 { color: #1f2937; margin-bottom: 8px; }
    table { border-collapse: collapse; width: 100%; margin-top: 14px; font-size: 12px; }
    th { background: #f0fdf4; color: #14532d; text-align: left; }
    th, td { border: 1px solid #d1d5db; padding: 9px; vertical-align: top; }
    .meta-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; }
    .meta-card { border: 1px solid #d1d5db; border-radius: 12px; padding: 12px; background: #f9fafb; }
    .severity-callout { border-left: 5px solid #76b900; background: #f0fdf4; padding: 12px; margin: 10px 0; }
    .severity-high { border-color: #dc2626; background: #fef2f2; }
    .severity-medium { border-color: #f59e0b; background: #fffbeb; }
    footer { margin-top: 24px; color: #6b7280; font-size: 11px; display: flex; justify-content: space-between; }
    @media print { body { background: white; } .report-page { box-shadow: none; margin: 0; width: 100%; min-height: 100vh; } a { color: inherit; text-decoration: none; } }
    /* page counter */`;
  if (report.report_type === "executive-summary") {
    const completedValidations = validations.filter((detail) => detail.validation.state === "completed").length;
    const failedValidations = validations.filter((detail) => ["failed", "timed_out", "cancelled"].includes(detail.validation.state)).length;
    const warningResults = validations.flatMap((detail) => detail.results).filter((result) => result.state === "unavailable" || result.state === "timed_out");
    const latestValidation = validations.slice().sort((left, right) => String(right.validation.completed_at ?? right.validation.created_at).localeCompare(String(left.validation.completed_at ?? left.validation.created_at)))[0] ?? null;
    const validationCoverage = validations.length ? `${completedValidations}/${validations.length} completed` : missing.validationNotRun;
    const readinessScore = validations.length ? `${Math.round((completedValidations / validations.length) * 100)}%` : missing.notAvailable;
    const benchmarkStatus = benchmarks.length ? unique(benchmarks.map((run) => run.status ?? missing.notAvailable)).join(", ") : missing.notAvailable;
    const trendDirection = validations.length < 2 ? missing.notAvailable : failedValidations ? "Needs attention" : "Stable";
    const criticalFindings = failedValidations + validations.flatMap((detail) => detail.results).filter((result) => result.state === "failed" || result.state === "timed_out").length;
    const warnings = warningResults.length + validations.filter((detail) => detail.validation.state === "queued" || detail.validation.state === "running").length;
    const topRisks = [
      ...(criticalFindings ? [`${criticalFindings} validation failure or timeout finding(s) require management attention.`] : []),
      ...(benchmarks.length ? [] : ["Benchmark status is not available for the selected live scope."]),
      ...(gpuIds.length ? [] : ["GPU inventory count is not available from selected live records."]),
      ...(warnings ? [`${warnings} warning or unavailable result(s) need follow-up evidence review.`] : []),
    ];
    const remediation = [
      ...(criticalFindings ? ["Resolve failed or timed-out validation evidence before acceptance." ] : []),
      ...(benchmarks.length ? [] : ["Collect benchmark evidence before making performance claims."]),
      ...(warningResults.length ? ["Re-run unavailable commands or document unsupported tools." ] : []),
    ];
    const finalRecommendation = criticalFindings ? "Do not approve final readiness until critical validation findings are remediated." : validations.length ? "Proceed with management review; preserve limitations for unavailable benchmark or telemetry fields." : "Collect live validation evidence before making a readiness recommendation.";
    const dataLimitations = [
      "Unavailable metrics are explicitly labeled; no simulated or fabricated measurements are used.",
      ...(benchmarks.length ? [] : ["Benchmark status is Not available." ]),
      ...(gpuIds.length ? [] : ["GPU count is Not collected from selected live evidence." ]),
      ...(validations.length ? [] : ["Validation status is Validation not run." ]),
    ];
    const itemList = (items: string[], emptyText: string) => `<ul>${(items.length ? items : [emptyText]).slice(0, 3).map((item) => `<li>${esc(item)}</li>`).join("")}</ul>`;
    const metric = (label: string, value: string | number) => `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;
    const executiveCss = `${css}
      .one-page-executive-summary { page-break-after: auto; padding: 34px; min-height: auto; }
      .exec-header { display: flex; justify-content: space-between; gap: 18px; border-bottom: 3px solid #76b900; padding-bottom: 12px; }
      .exec-title { margin: 6px 0 0; font-size: 34px; }
      .exec-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 8px; margin-top: 14px; }
      .metric { border: 1px solid #d1d5db; border-radius: 10px; padding: 8px; background: #f9fafb; min-height: 60px; }
      .metric span { display: block; color: #475569; font-size: 9px; text-transform: uppercase; letter-spacing: 0.08em; }
      .metric strong { display: block; margin-top: 4px; color: #0f172a; font-size: 14px; }
      .exec-columns { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; margin-top: 12px; }
      .exec-panel { border: 1px solid #d1d5db; border-radius: 12px; padding: 10px; background: white; }
      .exec-panel h3 { margin: 0 0 6px; font-size: 13px; color: #14532d; }
      .exec-panel ul { margin: 0; padding-left: 18px; font-size: 11px; line-height: 1.45; }
      .exec-footer { margin-top: 12px; border-top: 1px solid #e5e7eb; padding-top: 8px; font-size: 10px; color: #64748b; }
      @media print { .one-page-executive-summary { padding: 0; } .exec-title { font-size: 30px; } .exec-grid { gap: 6px; } .metric { min-height: 52px; } }`;
    const executivePage = `<section class="report-page one-page-executive-summary"><div class="exec-header"><div><div class="brand">GPUValidator</div><h1 class="exec-title">GPUValidator Executive Summary</h1><p><strong>Generated by Sabion P Frazier</strong><br><strong>Purpose: GPUValidator interview demonstration</strong></p></div><div><p><strong>Customer or engagement</strong><br>${present(report.customer ?? report.engagement_id, missing.notAvailable)}</p><p><strong>Selected cluster</strong><br>${present(report.cluster_id ?? report.scope_id, missing.notAvailable)}</p><p><strong>Generated date</strong><br>${esc(iso(generatedAt))}</p></div></div><div class="exec-grid">${[
      metric("Overall readiness score", readinessScore),
      metric("Connected agents", agents.length || missing.notAvailable),
      metric("Online agents", agents.filter((agent) => agent.status === "online").length || missing.notAvailable),
      metric("Node count", nodeIds.length || missing.notCollected),
      metric("GPU count", gpuIds.length || missing.notCollected),
      metric("Validation coverage", validationCoverage),
      metric("Latest validation status", latestValidation ? latestValidation.validation.state : missing.validationNotRun),
      metric("Benchmark status", benchmarkStatus),
      metric("Critical findings", criticalFindings),
      metric("Warnings", warnings),
      metric("Trend direction", trendDirection),
      metric("Report status", report.status),
    ].join("")}</div><div class="exec-columns"><div class="exec-panel"><h3>Top risks</h3>${itemList(topRisks, "No critical risks identified in selected live records.")}</div><div class="exec-panel"><h3>Outstanding remediation</h3>${itemList(remediation, "No outstanding remediation recorded in selected live records.")}</div><div class="exec-panel"><h3>Final recommendation</h3><ul><li>${esc(finalRecommendation)}</li></ul></div><div class="exec-panel"><h3>Data limitations</h3>${itemList(dataLimitations, "No data limitations recorded.")}</div></div><div class="exec-footer">Live source lineage: agents ${agentIds.map(esc).join(", ") || missing.notAvailable}; validations ${validationIds.map(esc).join(", ") || missing.validationNotRun}; benchmarks ${benchmarkIds.map(esc).join(", ") || missing.notAvailable}; GPUs ${gpuIds.map(esc).join(", ") || missing.notCollected}.</div></section>`;
    const executiveHtml = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${present(report.name)} | GPUValidator</title><style>${executiveCss}</style></head><body>${executivePage}</body></html>`;
    return {
      html: executiveHtml,
      metadata: {
        report_id: report.report_id,
        generated_at: generatedAt,
        html_sha256: crypto.createHash("sha256").update(executiveHtml).digest("hex"),
        source_lineage: { agent_ids: agentIds, node_ids: nodeIds, gpu_ids: gpuIds, validation_ids: validationIds, benchmark_ids: benchmarkIds, evidence_ids: evidenceIds },
      },
    };
  }
  const pages = [
    section("Cover Page", `<div class="brand">GPUValidator</div><h1>${present(report.name)}</h1><p><strong>Generated by Sabion P Frazier</strong></p><p><strong>Purpose: GPUValidator interview demonstration</strong></p><p>Customer: ${present(report.customer, missing.notAvailable)}</p><p>Confidentiality: ${present(report.confidentiality)}</p><footer><span>${present(report.report_id)}</span><span>Generated ${esc(iso(generatedAt))}</span></footer>`),
    section("Document Control", `<div class="meta-grid"><div class="meta-card"><strong>Version</strong><br>${present(report.version)}</div><div class="meta-card"><strong>Reviewer</strong><br>${present(report.reviewer, missing.notAvailable)}</div><div class="meta-card"><strong>Status</strong><br>${present(report.status)}</div><div class="meta-card"><strong>Time range</strong><br>${present(report.time_range)}</div></div>`),
    section("Generated By", `<p>Generated by Sabion P Frazier using GPUValidator live report rendering.</p><p>Author: ${present(report.author_name)}</p>`),
    section("Purpose", `<p>Purpose: GPUValidator interview demonstration</p><p>${present(report.purpose)}</p>`),
    section("Executive Summary", `<p>This report summarizes selected live GPUValidator agents, validation results, benchmark records, evidence references, and derived GPU inventory. Measurements appear only when present in selected source records.</p>${severity("Medium", "Missing source values are rendered as Not collected, Not available, Not supported, or Validation not run instead of fabricated measurements.")}`),
    section("Environment Summary", `<div class="meta-grid"><div class="meta-card"><strong>Agents</strong><br>${agents.length || missing.notAvailable}</div><div class="meta-card"><strong>Nodes</strong><br>${nodeIds.length || missing.notCollected}</div><div class="meta-card"><strong>GPUs</strong><br>${gpuIds.length || missing.notCollected}</div><div class="meta-card"><strong>Validations</strong><br>${validationIds.length || missing.validationNotRun}</div></div>`),
    section("Hardware Inventory", table(["Agent", "Hostname", "Status", "GPU count", "Capabilities"], hardwareRows, missing.notAvailable)),
    section("GPU Inventory", table(["Node", "Index", "Model", "UUID", "Memory", "Driver", "CUDA"], gpuRows, missing.notCollected)),
    section("Validation Results", table(["Validation", "Profile", "Command", "State", "Collected result"], validationRows, missing.validationNotRun)),
    section("Benchmark Results", table(["Benchmark", "Type", "Status", "Primary metric", "Node"], [...benchmarkRows, ...unresolvedBenchmarkRows], missing.notAvailable)),
    section("Findings", table(["Finding", "Severity", "Description"], findingRows, missing.notAvailable)),
    section("Risks", `${severity("Medium", "Operational risks depend on the selected validation and benchmark evidence. Missing benchmark or validation records require follow-up collection.")}<p>${missing.notSupported} indicates the source did not declare support for a capability.</p>`),
    section("Recommended Remediation", `<ul><li>Collect missing validation outputs marked ${missing.notCollected}.</li><li>Run validations marked ${missing.validationNotRun} before customer acceptance.</li><li>Review benchmark records marked ${missing.notAvailable} before performance claims.</li></ul>`),
    section("Evidence References", table(["Evidence", "Node", "Status", "Collected", "Missing", "Storage reference"], evidenceRows, missing.notAvailable)),
    section("Report Provenance", `<div class="meta-grid"><div class="meta-card"><strong>Report ID</strong><br>${present(report.report_id)}</div><div class="meta-card"><strong>Scope</strong><br>${present(report.scope_type)} / ${present(report.scope_id, missing.notAvailable)}</div><div class="meta-card"><strong>Validation IDs</strong><br>${validationIds.map(esc).join(", ") || missing.validationNotRun}</div><div class="meta-card"><strong>Benchmark IDs</strong><br>${benchmarkIds.map(esc).join(", ") || missing.notAvailable}</div><div class="meta-card"><strong>Agent IDs</strong><br>${agentIds.map(esc).join(", ") || missing.notAvailable}</div><div class="meta-card"><strong>Evidence IDs</strong><br>${evidenceIds.map(esc).join(", ") || missing.notAvailable}</div></div>`),
    section("Appendices", `<h3>Notes</h3><p>${present(report.notes, missing.notAvailable)}</p><h3>Missing-data legend</h3><ul><li>${missing.notCollected}</li><li>${missing.notAvailable}</li><li>${missing.notSupported}</li><li>${missing.validationNotRun}</li></ul>`),
  ];
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${present(report.name)} | GPUValidator</title><style>${css}</style></head><body>${pages.join("")}</body></html>`;
  return {
    html,
    metadata: {
      report_id: report.report_id,
      generated_at: generatedAt,
      html_sha256: crypto.createHash("sha256").update(html).digest("hex"),
      source_lineage: { agent_ids: agentIds, node_ids: nodeIds, gpu_ids: gpuIds, validation_ids: validationIds, benchmark_ids: benchmarkIds, evidence_ids: evidenceIds },
    },
  };
}
