export type LibraryCommand = { command: string; description: string; safety: "read-only" | "mutating" | "example"; category: string };
export type LibraryPage = { slug: string; title: string; category: string; overview: string; keyConcepts: string[]; commands: LibraryCommand[]; troubleshooting: string[]; safetyWarnings: string[]; interviewQuestions: string[]; relatedFeatures: string[]; lastReviewed: string };

export const libraryPages: LibraryPage[] = [
  {
    slug: "slurm", title: "Slurm Cheat Sheet", category: "Scheduler", overview: "Read-only inspection and controlled operational patterns for GPU clusters using Slurm.",
    keyConcepts: ["Partitions group nodes and scheduling policy.", "GRES describes GPU resources.", "Reservations, constraints, dependencies, and arrays shape placement.", "Pending reasons identify scheduler blockers."],
    commands: [
      { command: "sinfo -Nel", description: "Inspect nodes and states.", safety: "read-only", category: "Cluster inspection" }, { command: "squeue -o '%.18i %.9P %.30j %.8u %.2t %.10M %.6D %R'", description: "Queue with reasons.", safety: "read-only", category: "Cluster inspection" }, { command: "scontrol show nodes", description: "Detailed node inventory.", safety: "read-only", category: "Cluster inspection" }, { command: "scontrol show partition", description: "Partition configuration.", safety: "read-only", category: "Cluster inspection" }, { command: "scontrol show config", description: "Controller configuration.", safety: "read-only", category: "Cluster inspection" }, { command: "sacct -j <jobid> --format=JobID,State,Elapsed,AllocTRES", description: "Completed job accounting.", safety: "read-only", category: "Cluster inspection" }, { command: "sstat -j <jobid>.batch", description: "Live job statistics.", safety: "read-only", category: "Cluster inspection" },
      { command: "sbatch --gres=gpu:4 --exclusive job.sh", description: "Submit GPU batch job.", safety: "mutating", category: "Job operations" }, { command: "srun --gpus-per-node=4 --ntasks-per-node=4 --cpus-per-task=8 --exclusive ./all_reduce_perf", description: "Interactive GPU launch pattern.", safety: "mutating", category: "GPU examples" }, { command: "salloc --nodes=2 --gpus-per-node=4 --exclusive", description: "Allocate nodes interactively.", safety: "mutating", category: "Job operations" }, { command: "scancel <jobid>", description: "Cancel a job.", safety: "mutating", category: "Job operations" }, { command: "sbatch --array=0-15%4 job.sh", description: "Job array throttled concurrency.", safety: "mutating", category: "Job operations" }, { command: "sbatch --dependency=afterok:<jobid> job.sh", description: "Job dependency.", safety: "mutating", category: "Job operations" }, { command: "srun --nodes=2 --ntasks-per-node=4 --gpus-per-node=4 ./all_reduce_perf -b 8M -e 1G -f 2 -g 1", description: "Illustrative multi-node NCCL launch; validate MPI and fabric first.", safety: "example", category: "GPU examples" }
    ],
    troubleshooting: ["Check pending reasons in squeue and scontrol show job.", "Investigate drained nodes with scontrol show nodes and daemon logs.", "Compare configured GRES with nvidia-smi visibility.", "Review prolog/epilog failures before rerunning workloads.", "Inspect cgroup failures and slurmctld/slurmd logs."],
    safetyWarnings: ["Commands that submit, cancel, drain, resume, or modify nodes are mutating.", "Do not run multi-node NCCL during production workload windows without approval.", "Separate read-only triage from scheduler mutations."],
    interviewQuestions: ["How do you diagnose a pending GPU job?", "What is the difference between --gres and --gpus-per-node?", "How do reservations and constraints affect placement?"], relatedFeatures: ["Benchmark target selection", "Multi-node dry-run plans", "Readiness findings"], lastReviewed: "Last reviewed 2026-07 for Slurm 23/24 style commands; site options vary."
  },
  {
    slug: "lustre", title: "Lustre Cheat Sheet", category: "Storage", overview: "Parallel filesystem inspection, striping, capacity, inode, and client troubleshooting workflow.",
    keyConcepts: ["MDTs store metadata; OSTs store object data.", "Striping distributes file data across OSTs.", "Capacity and inode exhaustion fail differently.", "Client, MDS, and OSS health must be separated."],
    commands: [
      { command: "findmnt -t lustre", description: "Show mounted Lustre filesystems.", safety: "read-only", category: "Mounts" }, { command: "lfs df -h", description: "Capacity by MDT/OST.", safety: "read-only", category: "Capacity" }, { command: "lfs df -i", description: "Inode usage.", safety: "read-only", category: "Capacity" }, { command: "lfs check servers", description: "Server reachability check.", safety: "read-only", category: "Health" }, { command: "lfs getstripe <path>", description: "Read stripe layout.", safety: "read-only", category: "Striping" }, { command: "lfs setstripe -c 4 -S 16M <dir>", description: "Set stripe policy for new files in directory.", safety: "mutating", category: "Striping" }, { command: "lfs find <path> --size +1G", description: "Find large files.", safety: "read-only", category: "Triage" }, { command: "lfs quota -u <user> <mount>", description: "User quota.", safety: "read-only", category: "Quota" }, { command: "lctl dl", description: "List Lustre devices on client.", safety: "read-only", category: "Client" }, { command: "lctl get_param osc.*.stats", description: "Client/OSC counters.", safety: "read-only", category: "Performance" }, { command: "lctl ping <nid>", description: "Test LNet reachability.", safety: "read-only", category: "Network" }
    ],
    troubleshooting: ["Confirm mount and target visibility with findmnt and lfs df.", "Check for full OSTs vs full MDT inodes.", "Read stripe settings for hot directories.", "Use lctl counters for RPC/error clues.", "Interpret EIO/ENOSPC/ESTALE with client and server logs."],
    safetyWarnings: ["lfs setstripe is mutating and affects new file layout.", "Avoid destructive cleanup during evidence collection.", "Do not run write-heavy tests on shared production filesystems without approval."],
    interviewQuestions: ["How do OST and MDT exhaustion differ?", "When would you change stripe count?", "How do you triage a slow Lustre client?"], relatedFeatures: ["Evidence collection storage mounts", "Operations Library", "Acceptance report storage findings"], lastReviewed: "Last reviewed 2026-07; Lustre command availability varies by client version."
  },
  {
    slug: "base-command-manager", title: "NVIDIA Base Command Manager Cheat Sheet", category: "Cluster management", overview: "Conceptual and illustrative operational workflow for NVIDIA Base Command Manager (BCM). Exact commands vary by version and site configuration.",
    keyConcepts: ["cmsh is the primary interactive shell in many BCM deployments.", "Devices, categories, software images, and provisioning state are core concepts.", "CMDaemon coordinates cluster management.", "BCM often integrates monitoring, Slurm, GPU visibility, and provisioning."],
    commands: [
      { command: "cmsh", description: "Enter BCM shell; use help and tab completion for version-specific commands.", safety: "read-only", category: "Discovery" }, { command: "cmsh -c 'help'", description: "Command discovery entry point.", safety: "read-only", category: "Discovery" }, { command: "cmsh -c 'device; list'", description: "Illustrative device listing; verify syntax with help.", safety: "example", category: "Devices" }, { command: "cmsh -c 'category; list'", description: "Illustrative category inspection.", safety: "example", category: "Categories" }, { command: "cmsh -c 'softwareimage; list'", description: "Illustrative software image inspection.", safety: "example", category: "Images" }, { command: "cmsh -c 'monitoring; help'", description: "Discover monitoring commands for this version.", safety: "read-only", category: "Monitoring" }, { command: "cmsh -c 'device; status'", description: "Illustrative node state/health check; not universal.", safety: "example", category: "Health" }
    ],
    troubleshooting: ["Start with version and help output; do not assume command names are universal.", "Inspect device state, category assignment, and image assignment.", "Check provisioning state before Slurm symptoms.", "Correlate GPU visibility with node health and monitoring.", "Review BCM/CMDaemon logs using local site procedures."],
    safetyWarnings: ["Do not call it Base Commander; product name is NVIDIA Base Command Manager.", "Provisioning and category/image changes are mutating and site-specific.", "Use help/tab completion and vendor docs for exact commands."],
    interviewQuestions: ["How do categories and software images relate?", "What would you check before reprovisioning a node?", "How does BCM integrate with Slurm and GPU monitoring?"], relatedFeatures: ["Cluster intelligence", "Operations Library", "Runner readiness"], lastReviewed: "Last reviewed 2026-07 with version caveat: illustrative commands are not universal."
  },
  {
    slug: "benchmarks", title: "GPU Benchmark Cheat Sheet", category: "Benchmarking", overview: "NCCL Tests, NVIDIA HPL, DCGM diagnostics, inference benchmarking, and MLPerf boundary language.",
    keyConcepts: ["NCCL algbw measures algorithm bandwidth; busbw normalizes bus traffic.", "#wrong and out-of-bounds values are correctness signals.", "HPL uses N, NB, P, Q and residual correctness.", "Inference tracks throughput, latency, p95/p99, TTFT, and inter-token latency.", "Local benchmark results are not official MLPerf submissions."],
    commands: [
      { command: "make MPI=1 CUDA_HOME=/usr/local/cuda", description: "Build NCCL Tests when source is already approved and present.", safety: "mutating", category: "NCCL Tests" }, { command: "./all_reduce_perf -b 8M -e 1G -f 2 -g 4 -w 5 -n 20", description: "Single-node AllReduce smoke/perf pattern.", safety: "example", category: "NCCL Tests" }, { command: "./all_gather_perf -b 8M -e 1G -f 2 -g 4", description: "AllGather pattern.", safety: "example", category: "NCCL Tests" }, { command: "./reduce_scatter_perf -b 8M -e 1G -f 2 -g 4", description: "ReduceScatter pattern.", safety: "example", category: "NCCL Tests" }, { command: "./broadcast_perf -b 8M -e 1G -f 2 -g 4", description: "Broadcast pattern.", safety: "example", category: "NCCL Tests" }, { command: "NCCL_DEBUG=INFO NCCL_SOCKET_IFNAME=<iface> ./all_reduce_perf ...", description: "Transport discovery/troubleshooting; choose approved interface.", safety: "example", category: "NCCL Tests" }, { command: "NCCL_IB_DISABLE=1 ./all_reduce_perf ...", description: "Force non-IB path for troubleshooting only.", safety: "example", category: "NCCL Tests" }, { command: "dcgmi discovery -l", description: "DCGM discovery.", safety: "read-only", category: "DCGM" }, { command: "dcgmi diag -r 1", description: "DCGM level 1 diagnostics; approval recommended.", safety: "mutating", category: "DCGM" }, { command: "perf_analyzer -m <model> --concurrency-range 1:16:1", description: "Triton throughput/latency sweep.", safety: "example", category: "Inference" }, { command: "genai-perf profile --model <approved-model>", description: "GenAI-Perf profile using approved local model configuration.", safety: "example", category: "Inference" }
    ],
    troubleshooting: ["For NCCL hangs, check rank launch symmetry, transport interface, firewall, MPI, and NCCL_DEBUG output.", "Interpret #wrong > 0 as correctness failure, not just performance noise.", "For HPL, validate residual, rank/GPU mapping, affinity, and problem size.", "For inference, separate queue time from compute and tail latency.", "Do not imply official MLPerf compliance without the official harness, rules, and submission process."],
    safetyWarnings: ["Benchmarks can consume all selected GPUs.", "Do not download arbitrary models or containers during validation.", "MLPerf-style local testing is not an official MLPerf result."],
    interviewQuestions: ["What is busbw vs algbw?", "What does #wrong mean?", "How do P and Q map to HPL ranks?", "What are TTFT and inter-token latency?"], relatedFeatures: ["Benchmark definitions", "Benchmark jobs", "Node runner", "Benchmark result parsing"], lastReviewed: "Last reviewed 2026-07; examples require site approval before execution."
  }
];

export const libraryRoutes = ["/portal/library", "/portal/library/slurm", "/portal/library/lustre", "/portal/library/base-command-manager", "/portal/library/benchmarks"];

export function searchLibrary(query: string, category = "all"): LibraryPage[] {
  const terms = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  return libraryPages.filter((page) => {
    const haystack = [page.title, page.overview, page.category, ...page.keyConcepts, ...page.commands.flatMap((cmd) => [cmd.command, cmd.description, cmd.category]), ...page.troubleshooting].join(" ").toLowerCase();
    return (category === "all" || page.category === category) && (!terms.length || terms.every((term) => haystack.includes(term)));
  });
}
