import test from "node:test";
import assert from "node:assert/strict";

import { renderHtmlReport, reportHtmlSections } from "../src/server/report-renderer";
import type { ReportRecord } from "../src/server/reports";

const report: ReportRecord = {
  report_id: "rpt_render_test",
  schema_version: "1.0.0",
  name: "Live A100 Validation Report",
  report_type: "customer-validation",
  status: "draft",
  scope_type: "validation_run",
  scope_id: "val_live_1",
  customer: "NVIDIA interview demo",
  engagement_id: "eng_demo",
  cluster_id: "cluster_live",
  agent_ids: ["agt_live_1"],
  node_ids: ["3749527c40dd"],
  gpu_ids: ["GPU-live-0"],
  validation_ids: ["val_live_1"],
  benchmark_ids: ["bmk_live_1"],
  evidence_ids: ["res_live_1"],
  author_name: "Sabion P Frazier",
  purpose: "GPUValidator interview demonstration",
  confidentiality: "Confidential",
  time_range: "Last 24 hours",
  finding_ids: ["finding-live-warning"],
  include_evidence: true,
  include_raw_logs: false,
  include_charts: true,
  include_appendices: true,
  reviewer: "Technical reviewer",
  notes: "Renderer contract test",
  version: 1,
  created_at: "2026-07-21T10:00:00.000Z",
  updated_at: "2026-07-21T10:00:00.000Z",
  generated_at: null,
  checksum: "a".repeat(64),
  error: null,
};

const document = {
  validation_agents: [{ id: "agt_live_1", name: "runpod-a100x4-01", hostname: "3749527c40dd", gpu_count: 4, status: "online", capabilities: [{ name: "nvidia_smi_inventory", available: true }] }],
  validations: [{ id: "val_live_1", profile: "hardware-discovery", agent_id: "agt_live_1", state: "completed", created_at: "2026-07-21T10:01:00.000Z", completed_at: "2026-07-21T10:03:00.000Z" }],
  validation_jobs: [{ id: "job_live_1", validation_id: "val_live_1", command_type: "nvidia_smi_inventory", status: "completed" }],
  validation_results: [{ id: "res_live_1", validation_id: "val_live_1", job_id: "job_live_1", agent_id: "agt_live_1", state: "completed", stdout: "0, NVIDIA A100-SXM4-40GB, GPU-live-0", structured_result: { node_id: "3749527c40dd", gpus: [{ index: 0, name: "NVIDIA A100-SXM4-40GB", uuid: "GPU-live-0", memory_total: "40536 MiB", driver_version: "535.104.05" }] }, command_evidence: { command_type: "nvidia_smi_inventory" } }],
  benchmark_runs: [{ id: "bmk_live_1", benchmark_type: "nccl", status: "accepted", metrics: { bus_bandwidth_gbps: 191.5 }, node_id: "3749527c40dd", uploaded_at: "2026-07-21T10:04:00.000Z" }],
  evidence_records: [{ id: "evd_live_1", node_id: "3749527c40dd", ingestion_status: "accepted", collected_count: 6, missing_count: 1, failed_count: 0, storage_key: "evidence/live" }],
};

test("HTML renderer exposes all required professional report sections and print styling", () => {
  const rendered = renderHtmlReport(report, document);
  for (const section of reportHtmlSections) {
    assert.match(rendered.html, new RegExp(section), `${section} should be rendered`);
  }
  for (const required of ["Generated by Sabion P Frazier", "Purpose: GPUValidator interview demonstration", "GPUValidator", "@page", "page counter", "severity-callout", "Not collected", "Not available", "Not supported", "Validation not run"]) {
    assert.match(rendered.html, new RegExp(required), `${required} should be visible in HTML report`);
  }
});

test("HTML renderer includes selected live lineage without inventing measurements", () => {
  const rendered = renderHtmlReport(report, document);
  assert.equal(rendered.metadata.report_id, report.report_id);
  assert.deepEqual(rendered.metadata.source_lineage.validation_ids, ["val_live_1"]);
  assert.deepEqual(rendered.metadata.source_lineage.benchmark_ids, ["bmk_live_1"]);
  assert.deepEqual(rendered.metadata.source_lineage.agent_ids, ["agt_live_1"]);
  for (const actual of ["runpod-a100x4-01", "3749527c40dd", "NVIDIA A100-SXM4-40GB", "GPU-live-0", "535.104.05", "191.5", "val_live_1", "bmk_live_1", "res_live_1"]) {
    assert.match(rendered.html, new RegExp(actual.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${actual} should come from selected live source data`);
  }
  assert.doesNotMatch(rendered.html, /MLPerf|H100|B200|9999 GB\/s/);
}
);

test("executive summary renderer produces a one-page management report from selected live sources", () => {
  const rendered = renderHtmlReport({ ...report, report_type: "executive-summary", name: "GPUValidator Executive Summary" }, document, "2026-07-21T12:00:00.000Z");
  const requiredLabels = [
    "GPUValidator Executive Summary",
    "Customer or engagement",
    "Selected cluster",
    "Generated date",
    "Generated by Sabion P Frazier",
    "Purpose: GPUValidator interview demonstration",
    "Overall readiness score",
    "Connected agents",
    "Online agents",
    "Node count",
    "GPU count",
    "Validation coverage",
    "Latest validation status",
    "Benchmark status",
    "Critical findings",
    "Warnings",
    "Top risks",
    "Trend direction",
    "Outstanding remediation",
    "Final recommendation",
    "Data limitations",
  ];
  for (const label of requiredLabels) {
    assert.match(rendered.html, new RegExp(label), `${label} should appear in the executive summary`);
  }
  assert.match(rendered.html, /one-page-executive-summary/);
  assert.match(rendered.html, /NVIDIA interview demo/);
  assert.match(rendered.html, /cluster_live/);
  assert.match(rendered.html, /1\/1 completed/);
  assert.match(rendered.html, /accepted/);
  assert.match(rendered.html, /Unavailable metrics are explicitly labeled/);
  assert.equal((rendered.html.match(/class="report-page/g) ?? []).length, 1);
  assert.deepEqual(rendered.metadata.source_lineage.validation_ids, ["val_live_1"]);
  assert.deepEqual(rendered.metadata.source_lineage.agent_ids, ["agt_live_1"]);
  assert.deepEqual(rendered.metadata.source_lineage.gpu_ids, ["GPU-live-0"]);
  assert.doesNotMatch(rendered.html, /H100|B200|9999 GB\/s|simulated scenario/i);
});
